<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Public Panel</title>
    <link rel="icon" type="image/x-icon" href="{{ config('dashboard.favIcon') }}">
    @vite(['resources/sass/app.scss', 'resources/css/app.css', 'resources/js/app.js'])

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- multi-select -->
    <style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ asset('css/public/style.css') }}" />
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @php
        $authUser = auth()->check()
            ? auth()
                ->user()
                ->only(['first_name', 'last_name', 'full_name', 'email', 'phone'])
            : null;

        if ($authUser && auth()->user()->profile_img_media_id) {
            $authUser['profile_image'] = auth()->user()->profileImage();
        }
    @endphp

    <script>
        window.authUser = @json($authUser);
    </script>
</head>

<body>
    <div id="app" class="content">
        <public-header></public-header>
        <!-- Content -->
        @yield('content')
        <public-footer></public-footer>
        <app-component />
    </div>
    <script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


    <script src="https://js.stripe.com/v3/"></script>

    <!-- Custom JS -->
    <script src="{{ asset('js/public/script.js') }}"></script>
    <div id="public_ajax_loader" class="public_ajax_loader">
        <div class="ajax_loader_inner">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="150" height="150" style="shape-rendering: auto; display: block; background: transparent;"><g><circle fill="#003cbb" r="10" cy="50" cx="84">
            <animate begin="0s" keySplines="0 0.5 0.5 1" values="10;0" keyTimes="0;1" calcMode="spline" dur="0.25s" repeatCount="indefinite" attributeName="r"/>
            <animate begin="0s" values="#003cbb;#bfd9ff;#66a3ff;#0055fa;#003cbb" keyTimes="0;0.25;0.5;0.75;1" calcMode="discrete" dur="1s" repeatCount="indefinite" attributeName="fill"/>
            </circle><circle fill="#003cbb" r="10" cy="50" cx="16">
            <animate begin="0s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;10;10;10" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="r"/>
            <animate begin="0s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="cx"/>
            </circle><circle fill="#0055fa" r="10" cy="50" cx="50">
            <animate begin="-0.25s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;10;10;10" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="r"/>
            <animate begin="-0.25s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="cx"/>
            </circle><circle fill="#66a3ff" r="10" cy="50" cx="84">
            <animate begin="-0.5s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;10;10;10" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="r"/>
            <animate begin="-0.5s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="cx"/>
            </circle><circle fill="#bfd9ff" r="10" cy="50" cx="16">
            <animate begin="-0.75s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;10;10;10" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="r"/>
            <animate begin="-0.75s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="1s" repeatCount="indefinite" attributeName="cx"/>
            </circle><g/></g><!-- [ldio] generated by https://loading.io --></svg>
        </div>
    </div>
</body>

</html>
